package:
    name: conda-build-bug-example
    version: 1.0

source:
    path: ..

build:
    number: 0
    noarch: python

requirements:
    host:
        - python >=3.2
        - setuptools >=0.8
        - numpy
        - scipy
        - matplotlib
        - matrix-decomposition >0.7
        - overrides
    run:
        - python >=3.2
        - numpy
        - scipy
        - matplotlib
        - matrix-decomposition >0.7
        - overrides
